config/routes.rb
Investor::Application.routes.draw do

  resources :investment_asset_categories

  resources :investment_account_companies

  root :to => 'accounts#index'  
  
  match "/login", :to => "sessions#new", :as => "login"
  match "/auth/:provider/callback", :to => "sessions#create"
  match "/auth/failure", :to => "sessions#failure"
  match "/logout", :to =>  "sessions#destroy", :as => "logout"
  
  resources :investment_plans
  resources :portfolios
  resources :buy_lists, :only => [:create]
  
  resources :identities, :only => [:new]
  resources :investment_assets
  resources :plans
  resources :accounts
  resources :investment_accounts

end

app/models/portfolio.rb
require 'yahoo_stock'
require 'calculator'

class Portfolio < ActiveRecord::Base
  
  has_one :investment_plan

  has_many :portfolio_assets, :include => [:investment_asset], :order => 'percentage desc', :dependent => :destroy  
  accepts_nested_attributes_for :portfolio_assets, :allow_destroy => true, :reject_if => :all_blank
  
  belongs_to :user
    
  def current_asset_allocation
    rtn = {}
    total = 0
    return rtn if self.investment_plan.blank?
    self.investment_plan.investment_plan_assets.each do |ipa|
      sub_total = ipa.shares * ipa.investment_asset.current_value
      rtn[ipa.investment_asset_id] = sub_total
      total += sub_total
    end
    rtn.keys.each{|key| rtn[key] = rtn[key]/total }
    rtn
  end
    
  def clone(user_id)
    clone_portfolio = Portfolio.new(self.attributes.merge({:template => false, :user_id => user_id}))
    self.portfolio_assets.each do |pa|
      clone_portfolio.portfolio_assets << PortfolioAsset.create({:percentage => pa.percentage, :investment_asset_id => pa.investment_asset_id})
    end
    clone_portfolio.save
    clone_portfolio
  end  
  
  def buy_list_assets(investment_asset_id)
    rtn = []
    return rtn if self.investment_plan.blank?
    self.investment_plan.buy_lists.each do |bl|
      bl.buy_list_assets.each do |bla|
        rtn << bla if bla.investment_asset_id == investment_asset_id
      end
    end
    rtn
  end
  
  def total_return
    return 0 unless self.investment_plan.present? && self.investment_plan.buy_lists.present?
    transactions = []
    shares = {}
    self.investment_plan.buy_lists.each do |bl|
      bl.buy_list_assets.each do |bla|
        shares[bla.investment_asset_id] ||= 0
        transactions << {:value => -(bla.share_count * bla.share_price).as_currency, :date => bla.created_at}
        shares[bla.investment_asset_id] += bla.share_count
      end
    end
    current_value = 0
    shares.keys.each do |investment_asset_id|
      current_value += InvestmentAsset.find(investment_asset_id).current_value * shares[investment_asset_id]
    end
    transactions << {:value => current_value, :date => transactions.first[:date]} #Time.now
    Calculator.xirr(transactions, 0.05)
  end
  
  def portfolio_hash
    rtn = {}
    self.investment_plan.investment_plan_assets.each do |ipa|
      rtn[ipa.investment_asset_id] = {:asset_value => ipa.investment_asset.current_value, 
                                        :shares => ipa.shares, 
                                        :desired_percentage => self.portfolio_assets.select{|i| i.investment_asset_id == ipa.investment_asset_id }.first.percentage,
                                        :investment_asset => ipa.investment_asset                                        
                                      }
    end
    rtn
  end
  
  def historical(years=20, period='monthly', period_amount=500, trading_fee=0, create_csv=false)
    return {:compound_annual_growth => 0, :years => 0, :values => []} if self.portfolio_assets.blank?
    
    value_data = []
    csv_data = [['date', 'price']] if create_csv
    transactions = []
    days = years * 365
    self.portfolio_assets.each do |pa| 
      ah = AssetHistory.where(["investment_asset_id = ?", pa.investment_asset_id]).order('day asc').first
      puts "asset: #{pa.investment_asset_id} => #{ah.inspect}" if ah.blank?
      days_ago = Date.today - ah.day
      days = days_ago if days_ago < days
    end
    years = (years < days/365.0) ? years : days/365.0
    banked_value = 0
    total_invested_value = 0
    portfolio_assets = {}
    self.portfolio_assets.each{|pa| portfolio_assets[pa.investment_asset_id] = {:asset_value => 0, :shares => 0, :desired_percentage => pa.percentage, :asset => pa.investment_asset}}
    case period
    when 'monthly'
      months = (years * 12).to_i
      (0..months).each do |months_ago|
        next if months_ago == months
        amount_to_spend = banked_value + period_amount.to_f
        self.portfolio_assets.each do |pa|
          ah = AssetHistory.where(["investment_asset_id = ? and day >= ?", pa.investment_asset_id, (months - months_ago).months.ago]).order('day asc').first
          break if ah.blank?
          portfolio_assets[pa.investment_asset_id][:asset_value] = ((ah.open + ah.close)/2).as_currency
          dividends = AssetHistory.where(["investment_asset_id = ? and day >= ? and day < ? and dividend is not null", pa.investment_asset_id, 1.month.ago(ah.day), ah.day]).inject(0){|result,i| result + i.dividend}
          unless dividends == 0.0
            value = (portfolio_assets[pa.investment_asset_id][:shares] * dividends).round(4)
            amount_to_spend += value
          end
        end
        #puts "portfolio_assets: #{portfolio_assets.to_yaml}"
        buy_list = BuyList.generate_buy_list(portfolio_assets, amount_to_spend)
        sub_amount = 0
        buy_list.keys.each do |key|
          total_invested_value += portfolio_assets[key][:asset_value] * buy_list[key]
          amount_to_spend -= portfolio_assets[key][:asset_value] * buy_list[key]
          sub_amount += portfolio_assets[key][:asset_value] * buy_list[key]
        end
        #puts "total_invested_value: #{total_invested_value}"
        transactions << {:value => -(sub_amount).as_currency, :date => (months - months_ago).months.ago}
        csv_data << [(months - months_ago).months.ago.strftime('%m/%d/%Y'), -(sub_amount).as_currency] if create_csv #
        banked_value = amount_to_spend.as_currency
        
        # portfolio value
        portfolio_total = 0
        portfolio_assets.each_pair do |key, value|
          portfolio_total += (value[:asset_value] * value[:shares])
        end
        value_data << {:date => (months - months_ago).months.ago, :value => portfolio_total, :cost => total_invested_value} #.strftime('%m/%d/%Y')
        #puts "portfolio value: #{portfolio_total}"
      end
    end
    
    total_value = self.portfolio_assets.inject(0){|result, i| result + i.investment_asset.current_value * portfolio_assets[i.investment_asset_id][:shares]}
    transactions << {:value => total_value.as_currency, :date => 0.months.ago}
    csv_data << [0.months.ago.strftime('%m/%d/%Y'), total_value.as_currency] if create_csv
    
    if create_csv
      CSV.open("doc/#{self.name.gsub(' ','_').gsub('/','_')}.csv", "w") do |csv|
        csv_data.each do |row|
          csv << row
        end
      end
    end
    {:compound_annual_growth => (Calculator.xirr(transactions, 0.05) * 100).round(4), :years => (days.to_f/365).round(1), :data => value_data}
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_filter :authenticate

  # GET /portfolios
  # GET /portfolios.json
  def index
    if current_user
      @portfolios = Portfolio.where(["template = ? or user_id = ?", true, current_user.id])
    else
      @portfolios = Portfolio.where(["template = ?", true])      
    end
    
    historical = {}
    historical_data = @portfolios.map{|p| p.historical(10)[:data]}
    #portfolio_names = @portfolios.map{|p| p.historical(10)[:data]}
    historical_data.each_with_index do |portfolio, index|
      portfolio.each do |buy_item|
        #raise buy_item.inspect
        historical[buy_item[:date]] ||= {}
        historical[buy_item[:date]][@portfolios[index].name] = buy_item[:value]
      end
      #raise portfolio.inspect
    end
    
    names = ['Date', 'Cost']
    historical_values = []
    cost = 0
    historical.keys.sort.each do |date|
      cost += 500
      row = ["'#{date.strftime('%m/%d/%Y')}'", cost.to_s]
      historical[date].each_pair do |key, value|
        names << key unless names.include?(key)
        row << historical[date][key]
      end
      historical_values << "[#{row.join(",")}]"
    end
    names = names.map{|n| "'#{n}'"}
    historical_values.insert(0, names)
    #['Date', 'Value', 'Cost'],
#<%= @portfolio.historical(10)[:data].map{|row| "['#{row[:date]}', #{row[:value]}, #{row[:cost]}]"}.join(',') %>
    
    #@portfolios.each do |portfolio|
    #  names << portfolio.name
    #  historical << portfolio.historical(10)[:data].map{|row| "['#{row[:date]}', #{row[:value]}, #{row[:cost]}]"}.join(',')
    #end
    
    @graph_formatted = "[#{historical_values.join(',')}]"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @portfolios }
    end
  end

  # GET /portfolios/1
  # GET /portfolios/1.json
  def show
    @portfolio = Portfolio.find(params[:id])
    if @portfolio.template || (current_user && @portfolio.user_id == current_user.id)
      @total_value = @portfolio.portfolio_assets.inject(0){|sum, i| sum + i.shares * i.current_value}
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @portfolio }
      end
    else
      redirect_to portfolios_path, :notice => "You don't have permission to access that Portfolio"
    end
  end

  # GET /portfolios/new
  # GET /portfolios/new.json
  def new
    @portfolio = Portfolio.new
    @portfolio.user_id = current_user.id if current_user.present?
    @action = 'Create'
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @portfolio }
    end
  end

  # GET /portfolios/1/edit
  def edit
    @portfolio = Portfolio.includes(:portfolio_assets).find(params[:id])
    if current_user && @portfolio.user_id == current_user.id
      @action = 'Update'    
    else
      redirect_to portfolios_path, :notice => "You don't have permission to access that Portfolio"
    end
  end

  # POST /portfolios
  # POST /portfolios.json
  def create
    @portfolio = Portfolio.new(params[:portfolio])

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to @portfolio, :notice => 'Portfolio was successfully created.' }
        format.json { render :json => @portfolio, :status => :created, :location => @portfolio }
      else
        format.html { render :action => "new" }
        format.json { render :json => @portfolio.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /portfolios/1
  # PUT /portfolios/1.json
  def update
    @portfolio = Portfolio.find(params[:id])
    if current_user && @portfolio.user_id == current_user.id
      respond_to do |format|
        if @portfolio.update_attributes(params[:portfolio])
          format.html { redirect_to @portfolio, :notice => 'Portfolio was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @portfolio.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to portfolios_path, :notice => "You don't have permission to access that Portfolio"
    end
  end

  # DELETE /portfolios/1
  # DELETE /portfolios/1.json
  def destroy    
    @portfolio = Portfolio.find(params[:id])
    if current_user && @portfolio.user_id == current_user.id
      if @portfolio.investment_plan.present?
        redirect_to portfolio_path(@portfolio), :notice => "You have and Investment Plan that uses the portfolio: #{@portfolio.name}"
      else
        @portfolio.destroy

        respond_to do |format|
          format.html { redirect_to portfolios_url }
          format.json { head :ok }
        end
      end
    else
      redirect_to portfolios_path, :notice => "You don't have permission to access that Portfolio"
    end
  end
  
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  
end

app/views/portfolios/_form.html.erb
<%= form_for @portfolio, :html => {:class => 'well form-horizontal'} do |f| %>
  <% if @portfolio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@portfolio.errors.count, "error") %> prohibited this portfolio from being saved:</h2>

      <ul>
      <% @portfolio.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.hidden_field :user_id %>
	
	
	<fieldset>
		<div class="string clearfix required stringish control-group" id="portfolio_name_input">
	    <%= f.label :name, :class => 'control-label' %>
			<div class="controls">
	    	<%= f.text_field :name %>
			</div>
	  </div>
		<div class="string clearfix stringish control-group" id="portfolio_description_input">
	    <%= f.label :description, :class => 'control-label' %>
			<div class="controls">
	    	<%= f.text_area :description, {:size => '40x4'} %>
			</div>
	  </div>
		<div>
			<%= f.fields_for :portfolio_assets, f.object.portfolio_assets do |pa| %>
				<%= render :partial => "portfolio_asset_fields", :locals => {:f => pa} %>
			<% end %>
			<p><%= link_to_add_fields "New Asset", f, :portfolio_assets %></p>
		</div>
	</fieldset>
  <div class="actions">
    <%= f.submit "#{@action} Portfolio", :class => 'btn-primary btn commit create' %>
  </div>
<% end %>

app/views/portfolios/_portfolio_asset_fields.html.erb
<div style='padding-bottom: 10px;' class="portfolio_asset">
	<div class="string clearfix required stringish control-group" style='float:left;'>
		<%= f.label :asset_symbol, 'Stock Symbol', :class => 'control-label' %>
		<div class="controls">
			<%= f.text_field :asset_symbol, {:style => 'width: 50px;' } %>
		</div>
	</div>
	<div class="string clearfix required stringish control-group" style='float:left;'>
		<%= f.label :percentage, 'Portfolio Percentage', :class => 'control-label' %>
		<div class="controls">
			<%= f.text_field :percentage, {:style => 'width: 50px;margin-right:10px;', :class => 'percentage' } %>
		</div>
	</div>
	<div  style='float:left;'><%= link_to_remove_fields "remove", f %></div>
	<div style='clear:both'></div>
</div>

app/views/portfolios/edit.html.erb
<h1>Editing Portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<h1>Available Portfolios</h1>

<table class="table table-striped table-condensed table-outlined">
  <tr>
    <th>Name</th>
		<th>1 Year*</th>
		<th>3 Year*</th>
		<th>5 Year*</th>
		<th>10 Year*</th>
		<th>20 Year*</th>
    <th></th>
  </tr>

<% @portfolios.each do |portfolio| %>
  <tr>
    <td><%= link_to portfolio.name,  portfolio %></td>
		<td><%= (portfolio.one_year_return.blank?) ? 'N/A' : number_to_percentage(portfolio.one_year_return, :precision => 1) %></td>
		<td><%= (portfolio.three_year_return.blank?) ? 'N/A' : number_to_percentage(portfolio.three_year_return, :precision => 1) %></td>
		<td><%= (portfolio.five_year_return.blank?) ? 'N/A' : number_to_percentage(portfolio.five_year_return, :precision => 1) %></td>
		<td><%= (portfolio.ten_year_return.blank?) ? 'N/A' : number_to_percentage(portfolio.ten_year_return, :precision => 1) %></td>
		<td><%= (portfolio.twenty_year_return.blank?) ? 'N/A' : number_to_percentage(portfolio.twenty_year_return, :precision => 1) %></td>
    <td>
			<%= link_to 'Create Investment Plan', {:controller=>"investment_plans", :action=>"new", :portfolio_id => portfolio.id}, :class => 'btn btn-small btn-primary' %> 
			<%= link_to('Edit', edit_portfolio_path(portfolio), :class => 'btn btn-small') if portfolio.user == current_user %>
		</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Portfolio', new_portfolio_path, :class => 'btn btn-primary' %>

<br />
<div id='chart'></div>


<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {
        /*var data = google.visualization.arrayToDataTable([
                  
                  ['Date', 'Value', 'Cost'],
              <%#= @portfolio.historical(10)[:data].map{|row| "['#{row[:date]}', #{row[:value]}, #{row[:cost]}]"}.join(',') %>
                ]);
*/
        var data = google.visualization.arrayToDataTable(<%= @graph_formatted %>);
        var options = {
          title: 'Portfolio Performance',
          hAxis: {title: 'Date',  titleTextStyle: {color: 'red'}},
          height: 400,
          width: 800
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart'));
        chart.draw(data, options);
/*
        //var data = [<%#= @portfolio.historical(10)[:data].map{|i| "{date: #{i[:date]}, amount: #{i[:value]}}"}.join(', ') %>];

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('number', 'Value');
        data.addColumn('date', 'Date');
        data.addRows([
          <%#= @portfolio.historical(10)[:data].map{|i| "[#{i[:value]}, new Date(#{i[:date].year}, #{i[:date].month}, #{i[:date].day})]"}.join(', ') %>
        ]);

        // Set chart options
        var options = {'title':'Portfolio Value over time',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.BarChart(document.getElementById('chart'));
        chart.draw(data, options);
*/
      }
    </script>

<br />

<p>* All returns are calculating assuming a $500 a month contributions over the specified period.

app/views/portfolios/new.html.erb
<h1>New Portfolio</h1>

<%= render 'form' %>

app/views/portfolios/show.html.erb
<h1><%= @portfolio.name %></h1>
<% if @portfolio.description.present? %>
	<p><%= @portfolio.description %></p>
<% end %>
<table class="table table-striped table-condensed table-outlined">
	<tr>
		<th>Fund</th>
		<th>Category</th>
		<th>Desired Allocation</th>
		<%  if @portfolio.user == current_user && @portfolio.current_asset_allocation.present? %>
		<th>Current Allocation</th>
		<% end %>
		<th>Current Return</th>
	</tr>
	<% @portfolio.portfolio_assets.each do |pa| %>
		<tr>
			<td><%= link_to "#{pa.investment_asset.name.html_safe unless pa.investment_asset.blank?} (#{pa.investment_asset.symbol unless pa.investment_asset.blank?})", investment_asset_path(pa.investment_asset) %></td>
			<td><%= pa.investment_asset.investment_asset_category.name unless pa.investment_asset.blank? || pa.investment_asset.investment_asset_category.blank? %></td>
			<td><%= number_to_percentage(pa.percentage, :precision => 1) %></td>
			<%  if @portfolio.user == current_user && @portfolio.current_asset_allocation.present? %>
			<td><%= number_to_percentage(@portfolio.current_asset_allocation[pa.investment_asset_id] * 100, :precision => 1) %></td>
			<% end %>
			<td><%#= number_to_percentage(pa.calculate_return(@portfolio.buy_list_assets(pa.investment_asset_id)), :precision => 2) unless @portfolio.buy_list_assets(pa.investment_asset_id).blank? %></td>
		</tr>
	<% end %>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<%  if @portfolio.user == current_user && @portfolio.current_asset_allocation.present? %>
		<td>&nbsp;</td>
		<% end %>
		<td><b><%= number_to_percentage(@portfolio.total_return, :precision => 2) %></b></td>
	</tr>
</table>
<p>
	
	<% historic = @portfolio.historical(10) %>
	Historic Dollar Cost Average Return: <%= number_to_percentage(historic[:compound_annual_growth], :precision => 1) %> over <%= historic[:years] %> years</p>

<% if current_user && @portfolio.user_id == current_user.id %>
	<%= link_to 'Edit', edit_portfolio_path(@portfolio), :class => 'btn small primary' %>&nbsp;
	<%= link_to 'Delete', @portfolio, :confirm => 'Are you sure?', :method => :delete, :class => 'btn small danger' %>&nbsp;
<% else %>
	<%= link_to 'Clone', edit_portfolio_path(@portfolio), :class => 'btn btn-inverse' %>
<% end %>
<%= link_to 'Create Investment Plan',  {:controller=>"investment_plans", :action=>"new", :portfolio_id => @portfolio.id}, :class => 'btn btn-primary' %>
<div id='chart'></div>


<script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript">

      // Load the Visualization API and the piechart package.
      google.load('visualization', '1.0', {'packages':['corechart']});

      // Set a callback to run when the Google Visualization API is loaded.
      google.setOnLoadCallback(drawChart);

      // Callback that creates and populates a data table,
      // instantiates the pie chart, passes in the data and
      // draws it.
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
                  ['Date', 'Value', 'Cost'],
              <%= @portfolio.historical(10)[:data].map{|row| "['#{row[:date]}', #{row[:value]}, #{row[:cost]}]"}.join(',') %>
                ]);

        var options = {
          title: 'Portfolio Performance',
          hAxis: {title: 'Date',  titleTextStyle: {color: 'red'}},
          height: 400,
          width: 800
        };

        var chart = new google.visualization.AreaChart(document.getElementById('chart'));
        chart.draw(data, options);
/*
        //var data = [<%#= @portfolio.historical(10)[:data].map{|i| "{date: #{i[:date]}, amount: #{i[:value]}}"}.join(', ') %>];

        // Create the data table.
        var data = new google.visualization.DataTable();
        data.addColumn('number', 'Value');
        data.addColumn('date', 'Date');
        data.addRows([
          <%#= @portfolio.historical(10)[:data].map{|i| "[#{i[:value]}, new Date(#{i[:date].year}, #{i[:date].month}, #{i[:date].day})]"}.join(', ') %>
        ]);

        // Set chart options
        var options = {'title':'Portfolio Value over time',
                       'width':400,
                       'height':300};

        // Instantiate and draw our chart, passing in some options.
        var chart = new google.visualization.BarChart(document.getElementById('chart'));
        chart.draw(data, options);
*/
      }
    </script>