config/routes.rb
Investor::Application.routes.draw do

  resources :investment_asset_categories

  resources :investment_account_companies

  root :to => 'accounts#index'  
  
  match "/login", :to => "sessions#new", :as => "login"
  match "/auth/:provider/callback", :to => "sessions#create"
  match "/auth/failure", :to => "sessions#failure"
  match "/logout", :to =>  "sessions#destroy", :as => "logout"
  
  resources :investment_plans
  resources :portfolios
  resources :buy_lists, :only => [:create]
  
  resources :identities, :only => [:new]
  resources :investment_assets
  resources :plans
  resources :accounts
  resources :investment_accounts

end

app/models/investment_plan.rb
class InvestmentPlan < ActiveRecord::Base
  belongs_to :portfolio
  belongs_to :user
  
  has_many :buy_lists
  has_many :active_buy_lists, :class_name => 'BuyList', :conditions => {:purchased => false}
  has_many :investment_plan_assets
    
  validates_presence_of :name, :portfolio_id, :contribution_amount, :time_period, :start_date
  
  after_save :check_portfolio_assets
  
  def check_portfolio_assets
    portfolio_asset_hash = self.portfolio.portfolio_assets.inject({}){|result, i| result[i.investment_asset_id] = i; result}
    investment_plan_asset_hash = self.investment_plan_assets.inject({}){|result, i| result[i.investment_asset_id] = i; result}
    investment_asset_ids = portfolio_asset_hash.keys | investment_plan_asset_hash.keys
    investment_asset_ids.each do |ia_id|
      if portfolio_asset_hash.has_key?(ia_id) && !investment_plan_asset_hash.has_key?(ia_id)
        self.investment_plan_assets << InvestmentPlanAsset.new({:investment_asset_id => ia_id, :shares => 0})
      end
    end
  end
  
  def next_buy_date
    return self.start_date if self.start_date > Date.today
    if buy_lists.length == 0
      next_date(self.start_date)
    else
      date = next_date(self.start_date)
      while date < Date.today do
        date = next_date(date)
      end
      date
    end
  end
  
  def next_date(date)
    case self.time_period
    when 'Weekly'
      date + 1.week
    when 'Bi-Weekly'
      date + 2.week
    when 'Monthly'
      date + 1.month
    when 'Twice Monthly'
      if date.day > 15
        date - 15.days + 1.month
      else
        15.days.since(date)
      end
    end
  end
  
  
    
end

app/controllers/investment_plans_controller.rb
class InvestmentPlansController < ApplicationController
  before_filter :authenticate
  
  # GET /investment_plans
  # GET /investment_plans.json
  def index
    @investment_plans = (current_user) ? current_user.investment_plans : []

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @investment_plans }
    end
  end

  # GET /investment_plans/1
  # GET /investment_plans/1.json
  def show
    @investment_plan = InvestmentPlan.find(params[:id])
    if @investment_plan.user_id.blank? || (current_user && @investment_plan.user_id == current_user.id)
      contribution_amount = (@investment_plan.initial_contribution == 0 || @investment_plan.buy_lists.length > 0) ? @investment_plan.contribution_amount : @investment_plan.initial_contribution
      @buy_list = BuyList.buy_list_with_assets(@investment_plan.id, @investment_plan.portfolio.portfolio_hash, contribution_amount + @investment_plan.banked_value)

      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @investment_plan }
      end
    else
      redirect_to new_investment_plan_path, :notice => "You don't have permission to access that Investment Plan"
    end
  end

  # GET /investment_plans/new
  # GET /investment_plans/new.json
  def new
    @investment_plan = InvestmentPlan.new({:portfolio_id => params[:portfolio_id].to_i})
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @investment_plan }
    end
  end

  # GET /investment_plans/1/edit
  def edit
    @investment_plan = InvestmentPlan.find(params[:id])
    unless @investment_plan.user_id.blank? || (current_user && @investment_plan.user_id == current_user.id)
      redirect_to new_investment_plan_path, :notice => "You don't have permission to access that Investment Plan"
    end
  end

  # POST /investment_plans
  # POST /investment_plans.json
  def create
    params[:investment_plan][:user_id] = current_user.id if current_user
    portfolio = Portfolio.find(params[:investment_plan][:portfolio_id])
    if portfolio.template? || (current_user && portfolio.user_id == current_user.id)
      if portfolio.template?
        params[:investment_plan][:portfolio_id] = portfolio.clone(current_user.id).id
      end
      @investment_plan = InvestmentPlan.new(params[:investment_plan])
      @investment_plan.start_date = Date.strptime(params[:investment_plan][:start_date], '%m/%d/%Y') unless params[:investment_plan][:start_date].blank?
      respond_to do |format|
        if @investment_plan.save
          format.html { redirect_to @investment_plan, :notice => 'Investment plan was successfully created.' }
          format.json { render :json => @investment_plan, :status => :created, :location => @investment_plan }
        else
          format.html { render :action => "new" }
          format.json { render :json => @investment_plan.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to new_investment_plan_path, :notice => "You don't have permission to access that Portfolio"
    end
  end

  # PUT /investment_plans/1
  # PUT /investment_plans/1.json
  def update
    @investment_plan = InvestmentPlan.find(params[:id])
    portfolio = Portfolio.find(params[:investment_plan][:portfolio_id])
    if (@investment_plan.user_id.blank? || (current_user && @investment_plan.user_id == current_user.id)) && (portfolio.template? || (current_user && portfolio.user_id == current_user.id))      
      @investment_plan.start_date = Date.strptime(params[:investment_plan].delete(:start_date), '%m/%d/%Y') unless params[:investment_plan][:start_date].blank?
      respond_to do |format|
        if @investment_plan.update_attributes(params[:investment_plan])
          format.html { redirect_to @investment_plan, :notice => 'Investment plan was successfully updated.' }
          format.json { head :ok }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @investment_plan.errors, :status => :unprocessable_entity }
        end
      end
    else
      redirect_to new_investment_plan_path, :notice => "You don't have permission to access that Investment Plan"
    end
  end

  # DELETE /investment_plans/1
  # DELETE /investment_plans/1.json
  def destroy
    @investment_plan = InvestmentPlan.find(params[:id])
    if current_user && @investment_plan.user_id == current_user.id
      @investment_plan.destroy

      respond_to do |format|
        format.html { redirect_to investment_plans_url }
        format.json { head :ok }
      end
    else
      redirect_to new_investment_plan_path, :notice => "You don't have permission to access that Investment Plan"
    end
  end
end

app/helpers/investment_plans_helper.rb
module InvestmentPlansHelper
end

app/views/investment_plans/_form.html.erb
<div id="js-tabs">
	<ul>
		<li><a href="#tabs-1">Portfolio</a></li>
		<li><a href="#tabs-2">Details</a></li>
	</ul>

	<%= semantic_form_for @investment_plan, :html => {:class => 'well form-horizontal'} do |f| %>
	  <%= f.semantic_errors %>
	  <%= f.inputs do %>
			<div id='tabs-1'>
				<%= f.input :portfolio, :collection => Portfolio.where(["template = ? or user_id = ?", true, ((current_user) ? current_user.id : 0)]) %>
				<input type='button' value='Next' id='next_button' class='btn btn-primary commit create' /> <br /><br />
				<h4>Standard Portfolios</h4>
				<ul class='unstyled'>
				<% Portfolio.where({:template => true}).each do |p| %>
					<li>
						<strong><%= link_to p.name, '#', :id => "portfolio-#{p.id}", :class => 'portfolio' %></strong> 
						- <%= link_to 'View', portfolio_path(p), :target => 'new' %>
						<% if p.description.present? %>
							- <%= p.description %>
						<% end %>
					</li>
				<% end %>
				</ul>
				
				<% if current_user && Portfolio.where({:user_id => current_user.id}).length > 0 %>
					<h4>Custom Portfolios</h4>
					<ul class='unstyled'>
					<% Portfolio.where({:user_id => current_user.id}).each do |p| %>
						<li>
							<strong><%= link_to p.name, '#', :id => "portfolio-#{p.id}", :class => 'portfolio' %></strong> 
							- <%= link_to 'View', portfolio_path(p), :target => 'new' %>
							<% if p.description.present? %>
								- <%= p.description %>
							<% end %>
						</li>					
					<% end %>
					</ul>
				<% end %>
				<% if current_user %>
					<%= link_to 'New Portfolio', new_portfolio_path %>
				<% end %>
			</div>
			<div id='tabs-2'>
		    <%= f.input :name, :hint => "Give this plan a Name" %>
		    <%= f.input :initial_contribution, :hint => "How much do you currently have to invest?" %>
				<%= f.input :start_date, :as => :string, :hint => "When do you want to start contributing to this plan?", :input_html => {:class => 'datepicker'} %>
				<%= f.input :time_period, :collection => ['Weekly', 'Bi-Weekly', 'Twice Monthly', 'Monthly', 'Once'], :label => 'Contribution frequency', :hint => "How often would you like to contribute?" %>
				<%= f.input :contribution_amount, :hint => "How much can you contribute each time? (You can change this later if you'd like) " %>
				<%= f.input :email_updates, :label => 'Email Notifications' %>
			  <%= f.buttons do %>
			    <%= f.commit_button :button_html => {:class => "btn btn-primary"} %>
			  <% end %>
			</div>
	  <% end %>
	<% end %>
</div>

<script>
	$(function() {
		var $tabs = $( "#js-tabs" ).tabs();
		$('.portfolio').click(function(){
			$('#investment_plan_portfolio_id').val($(this).attr('id').split('-')[1]);
		});
		$('#next_button').click(function(){
			$tabs.tabs('select', 1);
		});
		<% if @investment_plan.portfolio.present? %>
			$tabs.tabs('select', 1);
		<% end %>
	});
</script>

app/views/investment_plans/edit.html.erb
<h1>Edit Your Investment Plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @investment_plan %> |
<%= link_to 'Back', investment_plans_path %>

app/views/investment_plans/index.html.erb
<h1>Investment Plans</h1>

<table class="table table-striped table-condensed table-outlined">
  <tr>
		<th>Name</th>
    <th>Portfolio</th>
    <th>Time period</th>
    <th>Start date</th>
    <th>Amount</th>
    <th></th>
  </tr>

<% @investment_plans.each do |investment_plan| %>
  <tr>
		<td><%= link_to investment_plan.name, investment_plan %></td>
    <td><%= link_to investment_plan.portfolio.name, portfolio_path(investment_plan.portfolio) %></td>
    <td><%= investment_plan.time_period %></td>
    <td><%= investment_plan.start_date.strftime('%m-%d-%Y') %></td>
    <td><%= number_to_currency(investment_plan.contribution_amount) %></td>
    <td><%= link_to 'Edit', edit_investment_plan_path(investment_plan), :class => 'btn  btn-primary' %> <%= link_to 'Remove', investment_plan, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Investment Plan', new_investment_plan_path, {:class => 'btn btn-primary'} %>

app/views/investment_plans/new.html.erb
<h1>Create Your Investment Plan</h1>

<%= render 'form' %>

<%= link_to 'Back', investment_plans_path %>

app/views/investment_plans/show.html.erb
<h1>Purchases for <%= @investment_plan.next_buy_date.strftime('%b %d, %Y') %></h1>
<%= form_for @buy_list do |f| %>
	<%= f.hidden_field :purchased, {:value => true} %>
	<%= f.hidden_field :investment_plan_id, {:value => @investment_plan.id} %>	
	<table class="table table-striped table-condensed table-outlined" style='width:700px'>
		<tr>
			<th>Count</th>
			<th>Fund Name</th>
			<th>Price</th>
		</tr>
		<%= f.fields_for :buy_list_assets do |bla| %>
			<tr>
				<td><%= bla.object.share_count %></td>
				<td>(<%= bla.object.investment_asset.symbol %>) <%= bla.object.investment_asset.name.html_safe %></td>
				<td><%= bla.text_field :share_price, :style => 'width:50px;' %></td>
			</tr>
			<%= bla.hidden_field :investment_asset_id %>
			<%= bla.hidden_field :share_count %>
			
		<% end %>
	<tr><td>&nbsp;</td><td>&nbsp;</td><td><b><%= number_to_currency(@buy_list.buy_list_assets.inject(0){|sum, i| sum + (i.share_count * i.share_price)}) %></b></td></tr>
</table>

	<%= f.submit('Mark as Purchased', {:class => "btn-primary"}) %>
<% end %>

<br />

<h2>Investment Plan: <%= @investment_plan.name %></h2>
<br />
<table class='table' style='width: 500px'>
	<tr>
		<th>Portfolio:</th>
		<td><%= link_to @investment_plan.portfolio.name, portfolio_path(@investment_plan.portfolio) %></td>
	</tr>
	<tr>
		<th>Time Period:</th>
		<td><%= @investment_plan.time_period %></td>
	</tr>
	<tr>
		<th>Contribution Start Date:</th>
		<td><%= @investment_plan.start_date.strftime('%b %d, %Y') %></td>
	</tr>
	<tr>
		<th><%= @investment_plan.time_period %> Contribution:</th>
		<td><%= number_to_currency(@investment_plan.contribution_amount) %></td>
	</tr>
	<tr>
		<th>Initial Contribution:</th>
		<td><%= number_to_currency(@investment_plan.initial_contribution) %></td>
	</tr>
	<tr>
		<th>Unspent Amount:</th>
		<td><%= number_to_currency(@investment_plan.banked_value) %></td>
	</tr>
	<tr>
		<th>Email Notification?</th>
		<td><%= (@investment_plan.email_updates?) ? 'Yes' : 'No' %></td>
	</tr>
</table>
<%= link_to 'Edit', edit_investment_plan_path(@investment_plan), :class => 'btn btn-primary' %>