config/routes.rb
Investor::Application.routes.draw do

  resources :investment_asset_categories

  resources :investment_account_companies

  root :to => 'accounts#index'  
  
  match "/login", :to => "sessions#new", :as => "login"
  match "/auth/:provider/callback", :to => "sessions#create"
  match "/auth/failure", :to => "sessions#failure"
  match "/logout", :to =>  "sessions#destroy", :as => "logout"
  
  resources :investment_plans
  resources :portfolios
  resources :buy_lists, :only => [:create]
  
  resources :identities, :only => [:new]
  resources :investment_assets
  resources :plans
  resources :accounts
  resources :investment_accounts

end

app/models/investment_asset.rb
class InvestmentAsset < ActiveRecord::Base
  has_many :portolio_assets
  has_many :buy_list_assets
  has_many :asset_histories, :order => 'day desc'
  has_many :investment_plan_assets

  has_many :investment_asset_investment_accounts
  has_many :investment_accounts, :through => :investment_asset_investment_accounts
  
  has_many :account_company_assets
  has_many :investment_account_companies, :through => :account_company_assets
  
  belongs_to :investment_asset_category

  before_create :verify_unique
  after_create :set_name_and_set_history
  
  before_save :set_category_hierarchy
  
  def set_category_hierarchy
    categories = []
    if self.investment_asset_category.present?
      more_categories = true
      category = self.investment_asset_category
      while more_categories
        categories << category.id
        if category.parent.present?
          category = category.parent
        else
          more_categories = false
        end
      end
    end
    self.category_hierarchy = "|#{categories.join('|')}|"
  end
  
  def verify_unique
    unless self.symbol.blank?
      self.symbol.upcase!
      if asset = InvestmentAsset.where(["symbol = ?", self.symbol]).first
        return asset
      end
    end
  end
  
  def set_name_and_set_history(set_name=true)    
    require 'yahoo_stock'
    require 'yahoo'

    if set_name && self.name.blank?
      quote = YahooStock::Quote.new(:stock_symbols => [self.symbol])
      quote.add_parameters(:name)
      results = quote.results(:to_hash).output
      self.update_attributes({:name => results.first[:name].strip.titleize, :current_value => results.first[:last_trade_price_only]})
    end
    
    if self.investment_asset_category_id.blank? || self.expense_ratio.blank?
      rtn = Yahoo.lookup(self.symbol)
      unless rtn[:category].blank?
        if self.investment_asset_category_id.blank?
          cat = InvestmentAssetCategory.find_or_create_by_key({:name => rtn[:category], :key => rtn[:category].downcase.strip})
          self.investment_asset_category_id = cat.id
        end
      end
      if self.expense_ratio.blank?
        self.expense_ratio = rtn[:expense_ratio]
      end
      self.save
    end

#=begin
    history = YahooStock::History.new(:stock_symbol => self.symbol, :start_date => Date.today - 30*365, :end_date => Date.today - 1)
    results = history.results(:to_hash).output
    results.each do |row|
      unless AssetHistory.exists?({:investment_asset_id => self.id, :day => Date.parse(row[:date])})
        AssetHistory.create({
            :investment_asset_id => self.id,
            :open => row[:open],
            :close => row[:close],
            :high => row[:high],
            :low => row[:low],
            :day => Date.parse(row[:date])
        })
        #puts "added: #{row[:date]}"
      end
    end
      
    history = YahooStock::History.new(:stock_symbol => self.symbol, :start_date => Date.today - 30*365, :end_date => Date.today - 1, :type => :dividend)
    results = history.results(:to_hash).output
    results.each do |row|
      ah = AssetHistory.where(['day = ? and investment_asset_id = ?', Date.parse(row[:date]), self.id]).first
      ah.update_attribute(:dividend, row[:dividends])
    end  
#=end
  end
  
  def set_name
    require 'open-uri'
    require 'json'
    unless self.symbol.blank?
      data = open("http://d.yimg.com/autoc.finance.yahoo.com/autoc?query=#{self.symbol}&callback=YAHOO.Finance.SymbolSuggest.ssCallback")
      line = data.each_line.first
      line = line.gsub!('YAHOO.Finance.SymbolSuggest.ssCallback(','')
      line = line.slice(0..line.length-2)
      result = JSON.parse(line)
      symbol = (result['ResultSet']['Result'].is_a?(Array)) ? result['ResultSet']['Result'].first : result['ResultSet']['Result']
      self.update_attribute(:name, symbol['name'])
    end
  end
end

app/controllers/investment_assets_controller.rb
class InvestmentAssetsController < ApplicationController
  before_filter :authenticate

  # GET /investment_assets
  # GET /investment_assets.json
  def index
    if current_user && current_user.admin?
      @investment_assets = InvestmentAsset.order('name')

      respond_to do |format|
        format.html # index.html.erb
      end
    else
      redirect_to accounts_path
    end
  end

  # GET /investment_assets/1
  # GET /investment_assets/1.json
  def show
    @investment_asset = InvestmentAsset.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /investment_assets/new
  # GET /investment_assets/new.json
  def new
    if current_user && current_user.admin?
      @investment_asset = InvestmentAsset.new

      respond_to do |format|
        format.html # new.html.erb
      end
    else
      redirect_to accounts_path
    end
  end

  # GET /investment_assets/1/edit
  def edit
    if current_user && current_user.admin?
      @investment_asset = InvestmentAsset.find(params[:id])
    else
      redirect_to accounts_path
    end
  end

  # POST /investment_assets
  # POST /investment_assets.json
  def create
    if current_user && current_user.admin?
      @investment_asset = InvestmentAsset.new(params[:investment_asset])

      respond_to do |format|
        if @investment_asset.save
          format.html { redirect_to @investment_asset, notice => 'Investment asset was successfully created.' }
        else
          format.html { render :action => "new" }
        end
      end
    else
      redirect_to accounts_path
    end
  end

  # PUT /investment_assets/1
  # PUT /investment_assets/1.json
  def update
    if current_user && current_user.admin?
      @investment_asset = InvestmentAsset.find(params[:id])

      respond_to do |format|
        if @investment_asset.update_attributes(params[:investment_asset])
          format.html { redirect_to({:controller => :investment_assets, :action => :index}, :notice => 'Investment asset was successfully updated.') }
        else
          format.html { render :action => "edit" }
        end
      end
    else
      redirect_to accounts_path
    end      
  end

  # DELETE /investment_assets/1
  # DELETE /investment_assets/1.json
  def destroy
    if current_user && current_user.admin?
      @investment_asset = InvestmentAsset.find(params[:id])
      @investment_asset.destroy

      respond_to do |format|
        format.html { redirect_to investment_assets_url }
        format.json { head :ok }
      end
    else
      redirect_to accounts_path
    end
  end
end

app/helpers/investment_assets_helper.rb
module InvestmentAssetsHelper
end

app/views/investment_assets/_form.html.erb
<%= semantic_form_for @investment_asset, :html => {:class => 'well form-horizontal'} do |f| %>
  <%= f.semantic_errors %>
  <%= f.inputs do %>
		<%= f.input :symbol %>
		<%= f.input :name %>
		<%= f.input :investment_asset_category, :collection => InvestmentAssetCategory.order('name') %>
		<%= f.input :expense_ratio %>
	<% end %>
  <%= f.buttons do %>
    <%= f.commit_button :button_html => {:class => "primary"} %>
  <% end %>	
<% end %>

app/views/investment_assets/edit.html.erb
<h1>Editing Investment Asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @investment_asset %> |
<%= link_to 'Back', investment_assets_path %>

app/views/investment_assets/index.html.erb
<h1>Listing Investment Assets</h1>

<table class='table table-striped'>
  <tr>
    <th>Symbol</th>
    <th>Name</th>
    <th>Category</th>
		<th>Expense Ratio</th>
    <th></th>
  </tr>

<% @investment_assets.each do |investment_asset| %>
  <tr>
		<td><%= investment_asset.symbol %></td>
		<td><%= investment_asset.name.html_safe %></td>
		<td><%= investment_asset.investment_asset_category.name unless investment_asset.investment_asset_category.blank? %></td>
		<td><%= investment_asset.expense_ratio %></td>
    <td><%= link_to 'Show', investment_asset %>&nbsp;&nbsp;
    <%= link_to 'Edit', edit_investment_asset_path(investment_asset) %>&nbsp;&nbsp;
    <%= link_to 'Destroy', investment_asset, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Investment asset', new_investment_asset_path %>

app/views/investment_assets/new.html.erb
<h1>New Investment Asset</h1>

<%= render 'form' %>

<%= link_to 'Back', investment_assets_path %>

app/views/investment_assets/show.html.erb
<p>
  <b>Name:</b>
  <%= @investment_asset.name %>
</p>

<p>
  <b>Symbol:</b>
  <%= @investment_asset.symbol %>
</p>

<p>
  <b>Category:</b>
  <%= @investment_asset.asset_category %>
</p>

<p>
  <b>Expense Ratio:</b>
  <%= @investment_asset.expense_ratio %>
</p>

<p>
  <b>Current Price:</b>
  <%= @investment_asset.current_value %>
</p>

<p>
	<b>Age:</b>
	<%= (Date.today - @investment_asset.asset_histories.last.day).to_i/365 unless @investment_asset.asset_histories.blank? %>
</p>

<%= link_to 'Edit', edit_investment_asset_path(@investment_asset) if current_user && current_user.admin? %>