config/routes.rb
Investor::Application.routes.draw do

  resources :investment_asset_categories

  resources :investment_account_companies

  root :to => 'accounts#index'  
  
  match "/login", :to => "sessions#new", :as => "login"
  match "/auth/:provider/callback", :to => "sessions#create"
  match "/auth/failure", :to => "sessions#failure"
  match "/logout", :to =>  "sessions#destroy", :as => "logout"
  
  resources :investment_plans
  resources :portfolios
  resources :buy_lists, :only => [:create]
  
  resources :identities, :only => [:new]
  resources :investment_assets
  resources :plans
  resources :accounts
  resources :investment_accounts

end

app/models/investment_account_company.rb
class InvestmentAccountCompany < ActiveRecord::Base
  attr_accessor :is_saved
  
  has_many :account_company_assets
  has_many :investment_assets, :through => :account_company_assets
  
  after_save :set_available_funds
  
  def set_available_funds
    if self.is_saved.blank? || !self.is_saved == true
      self.available_assets.split(/\s|,/).each do |symbol|
        next if symbol.strip.blank?
        investment_asset = InvestmentAsset.find_or_create_by_symbol({:symbol => symbol.strip.upcase})
        investment_assets << investment_asset unless investment_assets.include?(investment_asset)
      end
      self.is_saved = true
    end
  end
  
end

app/controllers/investment_account_companies_controller.rb
class InvestmentAccountCompaniesController < ApplicationController
  # GET /investment_account_companies
  # GET /investment_account_companies.json
  def index
    @investment_account_companies = InvestmentAccountCompany.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /investment_account_companies/1
  # GET /investment_account_companies/1.json
  def show
    @investment_account_company = InvestmentAccountCompany.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /investment_account_companies/new
  # GET /investment_account_companies/new.json
  def new
    @investment_account_company = InvestmentAccountCompany.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /investment_account_companies/1/edit
  def edit
    @investment_account_company = InvestmentAccountCompany.find(params[:id])
  end

  # POST /investment_account_companies
  # POST /investment_account_companies.json
  def create
    @investment_account_company = InvestmentAccountCompany.new(params[:investment_account_company])

    respond_to do |format|
      if @investment_account_company.save
        format.html { redirect_to @investment_account_company, :notice => 'Investment account company was successfully created.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /investment_account_companies/1
  # PUT /investment_account_companies/1.json
  def update
    @investment_account_company = InvestmentAccountCompany.find(params[:id])

    respond_to do |format|
      if @investment_account_company.update_attributes(params[:investment_account_company])
        format.html { redirect_to @investment_account_company, :notice => 'Investment account company was successfully updated.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /investment_account_companies/1
  # DELETE /investment_account_companies/1.json
  def destroy
    @investment_account_company = InvestmentAccountCompany.find(params[:id])
    @investment_account_company.destroy

    respond_to do |format|
      format.html { redirect_to investment_account_companies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/investment_account_companies_helper.rb
module InvestmentAccountCompaniesHelper
end

app/views/investment_account_companies/_form.html.erb
<%= semantic_form_for @investment_account_company, :html => {:class => 'well form-horizontal'} do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
    <%= f.input :available_assets %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/investment_account_companies/edit.html.erb
<h1>Editing Investment Account Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @investment_account_company %> |
<%= link_to 'Back', investment_account_companies_path %>

app/views/investment_account_companies/index.html.erb
<h1>Investment Account Companies</h1>

<table class='table table-striped'>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

<% @investment_account_companies.each do |investment_account_company| %>
  <tr>
    <td><%= link_to investment_account_company.name, investment_account_company %></td>
    <td>
			<%= link_to 'Edit', edit_investment_account_company_path(investment_account_company) %>
    	<%= link_to 'Destroy', investment_account_company, :confirm => 'Are you sure?', :method => :delete %>
		</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Investment account company', new_investment_account_company_path %>

app/views/investment_account_companies/new.html.erb
<h1>New Investment Account Company</h1>

<%= render 'form' %>

<%= link_to 'Back', investment_account_companies_path %>

app/views/investment_account_companies/show.html.erb
<p>
  <b>Name:</b>
  <%= @investment_account_company.name %>
</p>

<p>
  <b>Investment account:</b>
  <%= @investment_account_company.available_assets %>
</p>


<%= link_to 'Edit', edit_investment_account_company_path(@investment_account_company) %> |
<%= link_to 'Back', investment_account_companies_path %>